from .Persona import Persona
from .Paciente import Paciente
from .Doctor import Doctor
from .Asistente import Asistente
from .Usuario import Usuario
from .Cita import Cita
from .HistorialClinico import HistorialClinico
from .Factura import Factura
from .Consulta import Consulta
from .Enfermedad import Enfermedad
from .Tratamiento import Tratamiento
from .Pago import Pago